language: go
dist: xenial
sudo: true
services: [ docker ]
matrix:
  include:
    - os: linux
      go: 1.14.x

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: F019439LyMN7uT/PH6rSI/RGuLZxvqLfTYtJhnKwf4F7VZJMam+1PudDsA9phHxSSVuxXY7vbX76HT+OMLmTKxL9zIlO8QX7GGNOiySWqlxM6RLDzu9qZKY4Tt/XIq+N5bJ0/hEceRH+O0xicDfuhn9c0qtTiC2Q+QuAX8vHCaVUUexQqBHtDz+qizyVfFzdpTdY4v+X98IH5b4/0V+GAWJgBK8kmNOmCzI92YwOJWrGxNSpC7090YXbEJli6SaKatQohfQmiYCRiqyKe+RR012geczRW4wk8D9tux5M34KhU8gz46k3cL7YOCnAW6oO3CSUK2XfVQatOZ9vo24iJ8SUuGGzZzK+0KsUYgsXxi870eZ3FJkdgMS8E8TQ6tfpSpQMXTe9L39i9IVRtPm/aOMu8t6+0Xtz1h2A0V+KoxUx4W5K1VjPQkIrYjDLuND4m0SkJATyNkISCLy9alWVVWi2btIjrtrcLk4wksFKS/ECZFGkYgWZDzJw7UUh6WdivqLbOsGA+22pVhCsfb0zueAO4CLRkFrRdrQupmwErL7wblvNWtyn5/iBOrsr8rpd9c+A75zxAC6KBPluBJdUlJLGjjao3pJnFOMEy8dy83EfD2N5mHpe6j27zaVtGD1X+kkhMPjiiRbwK47vxxmcGIx0+5L43vK6utJEa3JQoVY=
  file_glob: true
  file:
    - bin/accounts-*
  on:
    repo: moov-io/accounts
    tags: true
    go: 1.14.x
  skip_cleanup: true

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push

